var searchData=
[
  ['safety_20and_20strong_20guarantees_0',['Exception Safety and Strong Guarantees',['../md_build_2md__files_2docs_2vector.html#autotoc_md108',1,'']]],
  ['sequence_20containers_1',['Sequence Containers',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md52',1,'']]],
  ['setup_20and_20usage_2',['setup and usage',['../md_build_2md__files_2docs_2Profiling.html#autotoc_md26',1,'Setup and Usage'],['../md_build_2md__files_2docs_2Profiling.html#autotoc_md30',1,'Setup and Usage'],['../md_build_2md__files_2docs_2Profiling.html#autotoc_md35',1,'Setup and Usage']]],
  ['size_3',['Capacity vs. Size',['../md_build_2md__files_2docs_2vector.html#autotoc_md97',1,'']]],
  ['smart_20pointers_4',['Smart Pointers',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md83',1,'']]],
  ['sort_5fbenchmark_2ecpp_5',['sort_benchmark.cpp',['../sort__benchmark_8cpp.html',1,'']]],
  ['started_6',['Getting Started',['../index.html#autotoc_md4',1,'']]],
  ['std_3a_3aarray_7',['std::array',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md56',1,'']]],
  ['std_3a_3adeque_8',['std::deque',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md54',1,'']]],
  ['std_3a_3aforward_5flist_9',['std::forward_list',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md57',1,'']]],
  ['std_3a_3alist_10',['std::list',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md55',1,'']]],
  ['std_3a_3amap_20and_20std_3a_3amultimap_11',['std::map and std::multimap',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md60',1,'']]],
  ['std_3a_3amultimap_12',['std::map and std::multimap',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md60',1,'']]],
  ['std_3a_3amultiset_13',['std::set and std::multiset',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md59',1,'']]],
  ['std_3a_3apriority_5fqueue_14',['std::queue and std::priority_queue',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md66',1,'']]],
  ['std_3a_3aqueue_20and_20std_3a_3apriority_5fqueue_15',['std::queue and std::priority_queue',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md66',1,'']]],
  ['std_3a_3aset_20and_20std_3a_3amultiset_16',['std::set and std::multiset',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md59',1,'']]],
  ['std_3a_3astack_17',['std::stack',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md65',1,'']]],
  ['std_3a_3aunordered_5fmap_20and_20std_3a_3aunordered_5fmultimap_18',['std::unordered_map and std::unordered_multimap',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md63',1,'']]],
  ['std_3a_3aunordered_5fmultimap_19',['std::unordered_map and std::unordered_multimap',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md63',1,'']]],
  ['std_3a_3aunordered_5fmultiset_20',['std::unordered_set and std::unordered_multiset',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md62',1,'']]],
  ['std_3a_3aunordered_5fset_20and_20std_3a_3aunordered_5fmultiset_21',['std::unordered_set and std::unordered_multiset',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md62',1,'']]],
  ['std_3a_3avector_22',['std::vector',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md53',1,'']]],
  ['std_3a_3avector_20tt_20in_20c_23',['In-Depth Guide to &lt;tt&gt;std::vector&lt;/tt&gt; in C++',['../md_build_2md__files_2docs_2vector.html',1,'']]],
  ['stl_24',['Comprehensive Guide to the C++ STL',['../md_build_2md__files_2docs_2stl__guide.html',1,'']]],
  ['stl_5fguide_2emd_25',['stl_guide.md',['../stl__guide_8md.html',1,'']]],
  ['storage_26',['Advantages of Contiguous Storage',['../md_build_2md__files_2docs_2vector.html#autotoc_md103',1,'']]],
  ['strategy_27',['strategy',['../md_build_2md__files_2docs_2vector.html#autotoc_md98',1,'Growth Strategy'],['../md_build_2md__files_2docs_2vector.html#autotoc_md96',1,'Memory Management and Growth Strategy']]],
  ['strong_20guarantees_28',['Exception Safety and Strong Guarantees',['../md_build_2md__files_2docs_2vector.html#autotoc_md108',1,'']]],
  ['structure_29',['Directory Structure',['../index.html#autotoc_md3',1,'']]]
];
