var searchData=
[
  ['c_0',['In-Depth Guide to &lt;tt&gt;std::vector&lt;/tt&gt; in C++',['../md_build_2md__files_2docs_2vector.html',1,'']]],
  ['c_2017_20and_20c_2020_1',['Parallel Algorithms (C++17 and C++20)',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md88',1,'']]],
  ['c_20projects_2',['Profiling Tools and Techniques for C++ Projects',['../md_build_2md__files_2docs_2Profiling.html',1,'']]],
  ['c_20stl_3',['Comprehensive Guide to the C++ STL',['../md_build_2md__files_2docs_2stl__guide.html',1,'']]],
  ['callgrind_4',['callgrind',['../md_build_2md__files_2docs_2Profiling.html#autotoc_md28',1,'Profiling with Valgrind (Callgrind)'],['../md_build_2md__files_2docs_2Profiling.html#autotoc_md29',1,'What is Valgrind/Callgrind?']]],
  ['capacity_20vs_20size_5',['Capacity vs. Size',['../md_build_2md__files_2docs_2vector.html#autotoc_md97',1,'']]],
  ['categories_6',['Iterator Categories',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md69',1,'']]],
  ['cd_7',['cd',['../index.html#autotoc_md13',1,'Continuous Integration (CI/CD)'],['../md_build_2md__files_2docs_2Profiling.html#autotoc_md40',1,'Integrating Profiling and Benchmarking in CI/CD']]],
  ['characteristics_8',['Key Characteristics',['../md_build_2md__files_2docs_2vector.html#autotoc_md95',1,'']]],
  ['ci_20cd_9',['ci cd',['../index.html#autotoc_md13',1,'Continuous Integration (CI/CD)'],['../md_build_2md__files_2docs_2Profiling.html#autotoc_md40',1,'Integrating Profiling and Benchmarking in CI/CD']]],
  ['code_20for_20profiling_10',['Preparing Your Code for Profiling',['../md_build_2md__files_2docs_2Profiling.html#autotoc_md22',1,'']]],
  ['common_20patterns_11',['Optimizing Common Patterns',['../md_build_2md__files_2docs_2vector.html#autotoc_md109',1,'']]],
  ['complexity_20guarantees_12',['Complexity Guarantees',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md74',1,'']]],
  ['components_13',['6. Utilities and Other Components',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md80',1,'']]],
  ['comprehensive_20guide_20to_20the_20c_20stl_14',['Comprehensive Guide to the C++ STL',['../md_build_2md__files_2docs_2stl__guide.html',1,'']]],
  ['conclusion_15',['conclusion',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md90',1,'8. Conclusion'],['../md_build_2md__files_2docs_2vector.html#autotoc_md110',1,'Conclusion'],['../md_build_2md__files_2docs_2Profiling.html#autotoc_md44',1,'Conclusion']]],
  ['considerations_16',['Performance Considerations',['../md_build_2md__files_2docs_2vector.html#autotoc_md102',1,'']]],
  ['construction_20and_20initialization_17',['Construction and Initialization',['../md_build_2md__files_2docs_2vector.html#autotoc_md100',1,'']]],
  ['container_20adaptors_18',['Container Adaptors',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md64',1,'']]],
  ['containers_19',['containers',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md51',1,'2. Containers'],['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md58',1,'Associative Containers'],['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md52',1,'Sequence Containers'],['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md61',1,'Unordered Associative Containers']]],
  ['contents_20',['contents',['../md_build_2md__files_2docs_2Profiling.html#autotoc_md18',1,'Table of Contents'],['../index.html#autotoc_md1',1,'Table of Contents'],['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md47',1,'Table of Contents']]],
  ['contiguous_20storage_21',['Advantages of Contiguous Storage',['../md_build_2md__files_2docs_2vector.html#autotoc_md103',1,'']]],
  ['continuous_20integration_20ci_20cd_22',['Continuous Integration (CI/CD)',['../index.html#autotoc_md13',1,'']]],
  ['contributing_23',['Contributing',['../index.html#autotoc_md14',1,'']]],
  ['costs_20of_20reallocation_24',['Costs of Reallocation',['../md_build_2md__files_2docs_2vector.html#autotoc_md104',1,'']]],
  ['cppdsa_25',['CppDSA',['../index.html',1,'']]],
  ['current_20landscape_26',['Current Landscape',['../md_build_2md__files_2docs_2Profiling.html#autotoc_md41',1,'']]],
  ['custom_20allocators_27',['custom allocators',['../md_build_2md__files_2docs_2stl__guide.html#autotoc_md87',1,'Custom Allocators'],['../md_build_2md__files_2docs_2vector.html#autotoc_md107',1,'Custom Allocators']]]
];
